// Supabase configuration
// Auto-generated by setup script

import { createClient } from '@supabase/supabase-js'

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Missing Supabase environment variables')
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: false, // We use Crossmint for auth
  },
  realtime: {
    params: {
      eventsPerSecond: Number(import.meta.env.VITE_REALTIME_EVENTS_PER_SECOND) || 10
    }
  },
  db: {
    schema: 'public'
  }
})

// Database configuration
export const DB_CONFIG = {
  poolSize: Number(import.meta.env.VITE_DB_POOL_SIZE) || 10,
  timeout: Number(import.meta.env.VITE_DB_TIMEOUT) || 30000,
}

// Real-time configuration
export const REALTIME_CONFIG = {
  eventsPerSecond: Number(import.meta.env.VITE_REALTIME_EVENTS_PER_SECOND) || 10,
  heartbeatInterval: Number(import.meta.env.VITE_REALTIME_HEARTBEAT_INTERVAL) || 30000,
}

// Platform configuration
export const PLATFORM_CONFIG = {
  feePercentage: Number(import.meta.env.VITE_PLATFORM_FEE_PERCENTAGE) || 5.0,
  minMarketDurationHours: Number(import.meta.env.VITE_MIN_MARKET_DURATION_HOURS) || 1,
  maxMarketDurationDays: Number(import.meta.env.VITE_MAX_MARKET_DURATION_DAYS) || 30,
}
